package View;

import Controller.ControleLogin;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author uniflduarte
 * @author unifpvalim
 */
public class LoginADMS extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginADMS() {
        initComponents();
        controle = new ControleLogin(this);
    }

    /**
     *
     * @return
     */
    public ControleLogin getControle() {
        return controle;
    }

    /**
     *
     * @param controle
     */
    public void setControle(ControleLogin controle) {
        this.controle = controle;
    }

    /**
     *
     * @return
     */
    public JButton getBtLogin() {
        return BtLogin;
    }

    /**
     *
     * @param BtLogin
     */
    public void setBtLogin(JButton BtLogin) {
        this.BtLogin = BtLogin;
    }

    /**
     *
     * @return
     */
    public JLabel getLblBemVindo() {
        return LblBemVindo;
    }

    /**
     *
     * @param LblBemVindo
     */
    public void setLblBemVindo(JLabel LblBemVindo) {
        this.LblBemVindo = LblBemVindo;
    }

    /**
     *
     * @return
     */
    public JLabel getLblCpf() {
        return LblCpf;
    }

    /**
     *
     * @param LblCpf
     */
    public void setLblCpf(JLabel LblCpf) {
        this.LblCpf = LblCpf;
    }

    /**
     *
     * @return
     */
    public JLabel getLblSenha() {
        return LblSenha;
    }

    /**
     *
     * @param LblSenha
     */
    public void setLblSenha(JLabel LblSenha) {
        this.LblSenha = LblSenha;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtCpf() {
        return TxtCpf;
    }

    /**
     *
     * @param TxtCpf
     */
    public void setTxtCpf(JTextField TxtCpf) {
        this.TxtCpf = TxtCpf;
    }

    /**
     *
     * @return
     */
    public JTextField getTxtSenha() {
        return TxtSenha;
    }

    /**
     *
     * @param TxtSenha
     */
    public void setTxtSenha(JTextField TxtSenha) {
        this.TxtSenha = TxtSenha;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtLogin = new javax.swing.JButton();
        LblBemVindo = new javax.swing.JLabel();
        LblCpf = new javax.swing.JLabel();
        TxtCpf = new javax.swing.JTextField();
        LblSenha = new javax.swing.JLabel();
        TxtSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BtLogin.setBackground(new java.awt.Color(102, 102, 255));
        BtLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtLogin.setText("LOGIN");
        BtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLoginActionPerformed(evt);
            }
        });

        LblBemVindo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LblBemVindo.setForeground(new java.awt.Color(0, 0, 102));
        LblBemVindo.setText("Bem vindo ao Exchange Cripto!");

        LblCpf.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LblCpf.setForeground(new java.awt.Color(0, 0, 102));
        LblCpf.setText("CPF :");

        LblSenha.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        LblSenha.setForeground(new java.awt.Color(0, 0, 102));
        LblSenha.setText("Senha:");

        TxtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LblSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblCpf)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                            .addComponent(TxtSenha))))
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(BtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(BtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLoginActionPerformed
        controle.LoginADM();
    }//GEN-LAST:event_BtLoginActionPerformed

    private void TxtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtSenhaActionPerformed

    }//GEN-LAST:event_TxtSenhaActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LoginADMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LoginADMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LoginADMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LoginADMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LoginADMS().setVisible(true);
//            }
//        });
//    }

    ControleLogin controle;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtLogin;
    private javax.swing.JLabel LblBemVindo;
    private javax.swing.JLabel LblCpf;
    private javax.swing.JLabel LblSenha;
    private javax.swing.JTextField TxtCpf;
    private javax.swing.JTextField TxtSenha;
    // End of variables declaration//GEN-END:variables
}
