
package View;

import Model.Administrador;
import Controller.Controle;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author uniflduarte
 * @author unifpvalim
 */

public class Menu extends javax.swing.JFrame {

   Administrador pessoa;

    /**
     *
     * @param pessoa
     */
    public Menu(Administrador pessoa) {
        initComponents();
        this.pessoa = pessoa;
        controle = new Controle(pessoa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtCadastrar = new javax.swing.JButton();
        BtExcluirInvestidor = new javax.swing.JButton();
        BtExcluirCripto = new javax.swing.JButton();
        BtCadastrarCripto = new javax.swing.JButton();
        BtSaldoInvestidor = new javax.swing.JButton();
        BtExtratoInvestidor = new javax.swing.JButton();
        BtAtulizar = new javax.swing.JButton();
        BtSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Exchange de Criptomoedas");

        BtCadastrar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BtCadastrar.setText("1. Cadastrar Investidor");
        BtCadastrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarActionPerformed(evt);
            }
        });

        BtExcluirInvestidor.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BtExcluirInvestidor.setText("2. Excluir Investidor");
        BtExcluirInvestidor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtExcluirInvestidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirInvestidorActionPerformed(evt);
            }
        });

        BtExcluirCripto.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BtExcluirCripto.setText("4. Excluir Cripto");
        BtExcluirCripto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtExcluirCripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirCriptoActionPerformed(evt);
            }
        });

        BtCadastrarCripto.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BtCadastrarCripto.setText("3. Cadastrar Cripto");
        BtCadastrarCripto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtCadastrarCripto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadastrarCriptoActionPerformed(evt);
            }
        });

        BtSaldoInvestidor.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BtSaldoInvestidor.setText("5. Consultar Saldo Investidor");
        BtSaldoInvestidor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtSaldoInvestidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSaldoInvestidorActionPerformed(evt);
            }
        });

        BtExtratoInvestidor.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BtExtratoInvestidor.setText("6. Consultar Extrato Investidor");
        BtExtratoInvestidor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtExtratoInvestidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExtratoInvestidorActionPerformed(evt);
            }
        });

        BtAtulizar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BtAtulizar.setText("7. Atualizar Cotação");
        BtAtulizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtAtulizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAtulizarActionPerformed(evt);
            }
        });

        BtSair.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        BtSair.setText("Sair");
        BtSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtSair, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtSaldoInvestidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtExtratoInvestidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtExcluirCripto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtAtulizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtCadastrarCripto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtExcluirInvestidor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtCadastrar)
                .addGap(18, 18, 18)
                .addComponent(BtExcluirInvestidor)
                .addGap(18, 18, 18)
                .addComponent(BtCadastrarCripto)
                .addGap(18, 18, 18)
                .addComponent(BtExcluirCripto)
                .addGap(18, 18, 18)
                .addComponent(BtSaldoInvestidor)
                .addGap(18, 18, 18)
                .addComponent(BtExtratoInvestidor)
                .addGap(18, 18, 18)
                .addComponent(BtAtulizar)
                .addGap(50, 50, 50)
                .addComponent(BtSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarActionPerformed
       try {
           controle.MenuCadastrarUsu();
       } catch (SQLException ex) {
           Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_BtCadastrarActionPerformed

    private void BtExcluirInvestidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirInvestidorActionPerformed
        ExcluirInvestidor excluirinvest = new ExcluirInvestidor(controle,pessoa);
        excluirinvest.setVisible(true);
    }//GEN-LAST:event_BtExcluirInvestidorActionPerformed

    private void BtExcluirCriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirCriptoActionPerformed
        ExcluirCripto excluircripto = new ExcluirCripto(controle,pessoa);
        excluircripto.setVisible(true);
    }//GEN-LAST:event_BtExcluirCriptoActionPerformed

    private void BtCadastrarCriptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadastrarCriptoActionPerformed
        CadastrarNovaCripto cadastrarcripto = new CadastrarNovaCripto(controle);
        cadastrarcripto.setVisible(true);
    }//GEN-LAST:event_BtCadastrarCriptoActionPerformed

    private void BtSaldoInvestidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSaldoInvestidorActionPerformed
        ConsultarSaldo saldo = new ConsultarSaldo(pessoa,controle);
        saldo.setVisible(true);
    }//GEN-LAST:event_BtSaldoInvestidorActionPerformed

    private void BtExtratoInvestidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExtratoInvestidorActionPerformed
        ConsultarExtrato extrato = new ConsultarExtrato(controle,pessoa);
        extrato.setVisible(true);
    }//GEN-LAST:event_BtExtratoInvestidorActionPerformed

    private void BtAtulizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAtulizarActionPerformed
       try {
           controle.Cotacoes();
       } catch (SQLException ex) {
           Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_BtAtulizarActionPerformed

    private void BtSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSairActionPerformed
        this.setVisible(false);
        LoginADMS login = new LoginADMS();
        login.setVisible(true);
    }//GEN-LAST:event_BtSairActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Menu().setVisible(true);
//            }
//        });
//    }

    Controle controle;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAtulizar;
    private javax.swing.JButton BtCadastrar;
    private javax.swing.JButton BtCadastrarCripto;
    private javax.swing.JButton BtExcluirCripto;
    private javax.swing.JButton BtExcluirInvestidor;
    private javax.swing.JButton BtExtratoInvestidor;
    private javax.swing.JButton BtSair;
    private javax.swing.JButton BtSaldoInvestidor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
